language: minimal

services:
  - docker

env:
  global:
    - TAG=${TRAVIS_BUILD_NUMBER}

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  # Build images (using Dockerfiles in each subdirectory)
  - docker build -t zabedin1999/udagram-api-feed:$TAG ./udagram-api-feed
  - docker build -t zabedin1999/udagram-api-user:$TAG ./udagram-api-user
  - docker build -t zabedin1999/udagram-frontend:$TAG ./udagram-frontend
  - docker build -t zabedin1999/reverseproxy:$TAG ./udagram-reverseproxy

after_success:
  # Push the tagged images to Docker Hub
  - docker push zabedin1999/udagram-api-feed:$TAG
  - docker push zabedin1999/udagram-api-user:$TAG
  - docker push zabedin1999/udagram-frontend:$TAG
  - docker push zabedin1999/reverseproxy:$TAG
