version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - backend-user
      - backend-feed
    
  backend-user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user
    ports:
      - "8081:8080"  # ADD THIS - map to different external port
    env_file:
      - .env
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      AWS_REGION: ${AWS_REGION}
      AWS_PROFILE: ${AWS_PROFILE}
      AWS_BUCKET: ${AWS_BUCKET}
      JWT_SECRET: ${JWT_SECRET}
      URL: ${URL}
      
  backend-feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed
    ports:
      - "8082:8080"  # ADD THIS - map to different external port
    env_file:
      - .env
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      AWS_REGION: ${AWS_REGION}
      AWS_PROFILE: ${AWS_PROFILE}
      AWS_BUCKET: ${AWS_BUCKET}
      JWT_SECRET: ${JWT_SECRET}
      URL: ${URL}
      
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local
    ports:
      - "8100:80"