name: Build and Push Docker images

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: zabedin1999
  IMAGE_TAG: ${{ github.run_number }}   # per-run numeric tag; change to github.sha if you prefer commit SHA

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-platform builds, optional)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push udagram-api-feed
        uses: docker/build-push-action@v4
        with:
          context: ./udagram-api-feed
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/udagram-api-feed:${{ env.IMAGE_TAG }}

      - name: Build and push udagram-api-user
        uses: docker/build-push-action@v4
        with:
          context: ./udagram-api-user
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/udagram-api-user:${{ env.IMAGE_TAG }}

      - name: Build and push udagram-frontend
        uses: docker/build-push-action@v4
        with:
          context: ./udagram-frontend
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/udagram-frontend:${{ env.IMAGE_TAG }}

      - name: Build and push reverseproxy
        uses: docker/build-push-action@v4
        with:
          context: ./udagram-reverseproxy
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/reverseproxy:${{ env.IMAGE_TAG }}

      # Optional: also push :latest tags (uncomment if you want)
      # - name: Tag and push latest for each image (optional)
      #   run: |
      #     docker pull $DOCKERHUB_USERNAME/udagram-api-feed:${IMAGE_TAG}
      #     docker tag $DOCKERHUB_USERNAME/udagram-api-feed:${IMAGE_TAG} $DOCKERHUB_USERNAME/udagram-api-feed:latest
      #     docker push $DOCKERHUB_USERNAME/udagram-api-feed:latest
      #     # repeat for other images...
